#!/usr/bin/env node
/**
 * Generates templates/scaffold/design-tokens.json — the single-file seed a scaffolded project
 * starts from — out of kit/tokens/*.json, and proves it with --check.
 *
 * Why generated: project-init 3.7a used to say "seeded from kit/tokens/" and leave the merge to
 * the agent. A literal merge builds 70 of 320 variables after seven silent key collisions. The
 * shape that builds at parity is specific (spec §4.4a):
 *   1. colors.json's tiers — primitive, semantic, component, dark — are hoisted to the top level,
 *      where the colour emitter reads them in single-file mode (build_tokens.mjs, step 3);
 *   2. every other file is keyed by its stem (typography, spacing, …) — exactly the directory-form
 *      paths GROUPS already reads;
 *   3. every {ref} is rewritten to a path that EXISTS in the result, chosen by existence rather
 *      than by rule order: data-viz.json and spacing.json both carry their own `semantic`, and
 *      states.json references shadows.json's `focus-ring` bare.
 *
 *   node scripts/make_single_file_tokens.mjs             # writes the seed
 *   node scripts/make_single_file_tokens.mjs --check     # exit 2 if the committed seed differs from a
 *                                                        # fresh generation, or does not build at parity
 *                                                        # with tokens/ under --strict (accuracy_report
 *                                                        # runs this on every /gate)
 */
import { readFileSync, readdirSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';

const KIT = fileURLToPath(new URL('../', import.meta.url)); // …/kit/
const TOKENS = join(KIT, 'tokens');
const argAfter = (flag) => (process.argv.includes(flag) ? process.argv[process.argv.indexOf(flag) + 1] : null);
const OUT = resolve(argAfter('--out') || join(KIT, '..', 'templates', 'scaffold', 'design-tokens.json'));
const CHECK = process.argv.includes('--check');
const TIERS = ['primitive', 'semantic', 'component', 'dark'];

const files = readdirSync(TOKENS).filter(n => n.endsWith('.json')).sort();
const data = Object.fromEntries(files.map(f => [f.replace(/\.json$/, ''), JSON.parse(readFileSync(join(TOKENS, f), 'utf8'))]));
const stems = Object.keys(data);
if (!data.colors) throw new Error('kit/tokens/colors.json is required');
for (const t of TIERS) if (stems.includes(t)) throw new Error(`kit/tokens/${t}.json would collide with the hoisted colour tier "${t}"`);

// 1–2) the shape
const seed = {
  $schema: 'https://design-tokens.github.io/community-group/format/',
  $description: 'GENERATED by kit/scripts/make_single_file_tokens.mjs from kit/tokens/*.json — do not edit. Colour tiers are top-level; every other token file is keyed by its stem. Regenerate: node kit/scripts/make_single_file_tokens.mjs. Verified on every /gate: --check.',
};
for (const t of TIERS) if (t in data.colors) seed[t] = data.colors[t];
for (const s of stems) if (s !== 'colors') seed[s] = data[s];

// every path in the result — groups and leaves — so a rewrite can be chosen by existence
const paths = new Set();
(function walk(o, p) {
  if (!o || typeof o !== 'object' || Array.isArray(o)) return;
  for (const [k, v] of Object.entries(o)) {
    if (k.startsWith('$')) continue;
    const q = p ? `${p}.${k}` : k;
    paths.add(q);
    walk(v, q);
  }
})(seed, '');

// 3) rewrite refs, by existence
function rewrite(ref, stem) {
  let r = ref.trim();
  while (r.startsWith('../') || r.startsWith('./')) r = r.startsWith('../') ? r.slice(3) : r.slice(2);
  const candidates = [
    r,                                                             // already real: a hoisted tier, or stem-qualified
    stem !== 'colors' ? `${stem}.${r}` : null,                     // intra-file: {fontSize.2xl} inside typography.json
    r.startsWith('colors.') ? r.slice('colors.'.length) : null,    // {../colors.semantic.x} → hoisted
    ...stems.filter(s => s !== stem && s !== 'colors').map(s => `${s}.${r}`), // bare into another file: {focus-ring}
  ].filter(Boolean);
  const hit = candidates.find(c => paths.has(c));
  if (!hit) throw new Error(`{${ref}} in ${stem}.json resolves to nothing in the seed`);
  return hit;
}
// Only values are rewritten — a $description that happens to contain braces is prose.
function rewriteAll(node, stem) {
  if (typeof node === 'string') return node.replace(/\{([^}]+)\}/g, (_, ref) => `{${rewrite(ref, stem)}}`);
  if (Array.isArray(node)) return node.map(n => rewriteAll(n, stem));
  if (node && typeof node === 'object') {
    return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, k.startsWith('$') && k !== '$value' ? v : rewriteAll(v, stem)]));
  }
  return node;
}
for (const t of TIERS) if (t in seed) seed[t] = rewriteAll(seed[t], 'colors');
for (const s of stems) if (s !== 'colors') seed[s] = rewriteAll(seed[s], s);

const text = JSON.stringify(seed, null, 2) + '\n';

if (!CHECK) {
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT} (${paths.size} paths)`);
  process.exit(0);
}

// --check: the committed seed is current, and builds at parity with the directory
let fail = 0;
let current = '';
try { current = readFileSync(OUT, 'utf8'); } catch { /* a missing seed is drift */ }
if (current !== text) {
  console.error(`DRIFT: ${OUT} differs from a fresh generation — run: node kit/scripts/make_single_file_tokens.mjs`);
  fail = 2;
}

// Every emitted line, sorted: names AND values. Order differs between layouts; nothing else may.
const build = (input) => execFileSync('node', [join(KIT, 'scripts', 'build_tokens.mjs'), '--in', input, '--strict'],
  { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).split('\n').filter(l => /^\s+--/.test(l)).map(l => l.trim()).sort();

const tmp = mkdtempSync(join(tmpdir(), 'seed-'));
try {
  writeFileSync(join(tmp, 'design-tokens.json'), text);
  const dir = build(TOKENS);
  const single = build(join(tmp, 'design-tokens.json'));
  const missing = dir.filter(l => !single.includes(l));
  const extra = single.filter(l => !dir.includes(l));
  if (missing.length || extra.length) {
    console.error(`PARITY: directory build ${dir.length} lines, single-file build ${single.length}`);
    for (const l of missing.slice(0, 10)) console.error(`  missing in single-file: ${l}`);
    for (const l of extra.slice(0, 10)) console.error(`  extra in single-file:   ${l}`);
    fail = 2;
  } else if (!fail) {
    console.log(`OK: seed is current and builds at parity (${dir.length} lines in both layouts, --strict clean)`);
  }
} catch (e) {
  console.error(`PARITY: a build failed — ${(e.stderr || e.message || '').toString().trim()}`);
  fail = 2;
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
process.exit(fail);
